modLoader="javafml" #mandatory
loaderVersion="[46,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="LGPL-2.1"

[[mods]] #mandatory
modId="celestial_forge" #mandatory
version="1.1.7" #mandatory
displayName="Celestial Forge" #mandatory
logoFile="logo.png" #optional
authors="Xiaoyue" #optional

# The description text for the mod (multi line!) (#mandatory)
description=''''''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.celestial_forge]] #optional
modId="forge" #mandatory
mandatory=true #mandatory
versionRange="[46,)" #mandatory
ordering="NONE"
side="BOTH"
[[dependencies.celestial_forge]]
modId="minecraft"
mandatory=true
versionRange="[1.20,1.21)"
ordering="NONE"
side="BOTH"
[[dependencies.celestial_forge]]
modId="celestial_core"
mandatory=false
versionRange="[1.5.0,)"
ordering="NONE"
side="BOTH"